### ISSUE TITLE
Polymorphic Node.js

### ISSUE THREAD

**Issue by RichardBruskiewich** [sfu-ireceptor/turnkey-service#2]
We need to efficiently support variants of the iReceptor Node.js implementation of the data node, e.g. VDJServer and Turnkey.

Scott Christley suggests the following strategy:

_One idea is to have the custom code in their own files, but have them all available in the master source code branch. For example:

Vdjserver.js
Gdc.js
Something_else.js

Then a configure option in the .env file would define which one to use:

Custom_file=Vdjserver.js

And in the actual javascript code, it could load that customization:

var custom_code = require(Custom_file);
 
For that to work, we would need to define a common set of functions that the customization code would all implement (with empty function if they don’t need to do anything). This might be possible because it seems there are two main customization areas
 
Handling/transform fields coming in to properly construct a query.
Handling/transform fields that are returned in the response._

**Comment by schristley** [comment]
@RichardBruskiewich I've written an implementation according to the discussed design. It is sitting on the [develop branch](https://github.com/sfu-ireceptor/service-js-mongodb/tree/develop). The customization files are stored in the config directory. There is a base template.js with function stubs, and you can see vdjserver.js which has all of the VDJServer customizations. It seems to work pretty well.

**Comment by schristley** [comment]
@RichardBruskiewich Note that I merged develop into master before I start doing work. I probably should have done the work on a separate branch but I suppose that's what develop is for too. I suppose you could try to merge develop into your turnkey-develop branch, but what might be better is for you to checkout develop, add a turnkey customization file, and see if you can get the turnkey working. That might also illuminate any other customizations on your turnkey-develop that maybe we didn't notice before.

**Comment by bcorrie** [comment]
Cleaning up - no longer used so closing.
